spring.application.name=back_ink
spring.datasource.url=jdbc:postgresql://localhost:5432/theinkdb
spring.datasource.username=theink
spring.datasource.password=theink
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
